//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Data.PostgreSql.DapperConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaptureSqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptureSqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Data.PostgreSql.DapperConfiguration.CaptureSqlQueries", typeof(CaptureSqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sbdh.contactinformation(id, header_id, type, identifier, contact, email, fax_number, phone_number, type_identifier) VALUES(@id, @headerid, @type, @identifier, @contact, @emailaddress, @faxnumber, @telephonenumber, @contacttypeidentifier) ...;.
        /// </summary>
        public static string Store_ContactInformationDto {
            get {
                return ResourceManager.GetString("Store_ContactInformationDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.error_declaration_eventid(request_id, event_id, corrective_eventid) VALUES(@requestid, @eventid, @id) ...;.
        /// </summary>
        public static string Store_CorrectiveIdDto {
            get {
                return ResourceManager.GetString("Store_CorrectiveIdDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.custom_field(request_id, event_id, field_id, parent_id, namespace, name, type, text_value, numeric_value, date_value) VALUES (@requestid, @eventid, @id, @parentid, @namespace, @name, @type, @textvalue, @numericvalue, @datevalue) ...;.
        /// </summary>
        public static string Store_CustomFieldDto {
            get {
                return ResourceManager.GetString("Store_CustomFieldDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.epc(request_id, event_id, epc, type, is_quantity, quantity, unit_of_measure) VALUES (@requestid, @eventid, @id, @type, @isquantity, @quantity, @unitofmeasure) ...;.
        /// </summary>
        public static string Store_EpcDto {
            get {
                return ResourceManager.GetString("Store_EpcDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.event(request_id, id, record_time, action, event_type, event_timezone_offset, business_location, business_step, disposition, read_point, transformation_id, event_id, errordeclaration_time, errordeclaration_reason) VALUES(@requestid, @id, @eventtime, @action, @type, @eventtimezoneoffset, @businesslocation, @businessstep, @disposition, @readpoint, @transformationid, @eventid, @ErrorDeclarationTime, @ErrorDeclarationReason) ...;.
        /// </summary>
        public static string Store_EventDto {
            get {
                return ResourceManager.GetString("Store_EventDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.request(document_time, record_time, user_id) VALUES(@documenttime, @recordtime, @userid) RETURNING id;.
        /// </summary>
        public static string Store_RequestDto {
            get {
                return ResourceManager.GetString("Store_RequestDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.source_destination(request_id, event_id, type, source_dest_id, direction) VALUES (@requestid, @eventid, @type, @id, @direction) ...;.
        /// </summary>
        public static string Store_SourceDestDto {
            get {
                return ResourceManager.GetString("Store_SourceDestDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sbdh.standardheader(id, version, standard, type_version, identifier, type, creation_datetime) VALUES(@id, @version, @standard, @typeversion, @instanceidentifier, @type, @creationdatetime);.
        /// </summary>
        public static string Store_StandardHeaderDto {
            get {
                return ResourceManager.GetString("Store_StandardHeaderDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO callback.query_callback(request_id, subscription_id, callback_type) VALUES(@requestid, @subscriptionid, @callbacktype);.
        /// </summary>
        public static string Store_SubscriptionCallbackDto {
            get {
                return ResourceManager.GetString("Store_SubscriptionCallbackDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO epcis.business_transaction(request_id, event_id, transaction_type, transaction_id) VALUES (@requestid, @eventid, @type, @id) ...;.
        /// </summary>
        public static string Store_TransactionDto {
            get {
                return ResourceManager.GetString("Store_TransactionDto", resourceCulture);
            }
        }
    }
}
