language: csharp
mono: none
sudo: required
dist: xenial
solution: FasTnT.sln
dotnet: 2.2
services:
 - postgresql
before_script:
 - psql -c 'create database fastnt_test;' -U postgres
 - psql -c "CREATE USER fastnt_user WITH PASSWORD 'pwd';" -U postgres
 - psql -c "GRANT ALL PRIVILEGES ON DATABASE fastnt_test TO fastnt_user;" -U postgres
 - dotnet user-secrets set ConnectionStrings:FasTnT.Database "Server=localhost;Database=fastnt_test;Port=5432;User Id=fastnt_user;Password=pwd;" -p test/FasTnT.IntegrationTests/FasTnT.IntegrationTests.csproj
script:
 - dotnet restore
 - dotnet test test/FasTnT.UnitTest/FasTnT.UnitTest.csproj
 - dotnet test test/FasTnT.IntegrationTests/FasTnT.IntegrationTests.csproj
