//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Handlers.DatabaseSetup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseSqlRequests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseSqlRequests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Handlers.DatabaseSetup.DatabaseSqlRequests", typeof(DatabaseSqlRequests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAA/+1b3XKjOBa+jp9Cleqt2LseV346nc6k5gJjOWHaAQ/g9PTeUARwTLUNbn7Sk3m1vdhH2lfYIyEw/xCb7PTFpqrdCZKOjr7vk3SOkP/zr3//9BNaKFhWkMLf4Xuux8uYUzH7CwlTJEoqwr8Liqqg0Lc8/yauonLjGS6rMSKfvX4PwY9tIrAucDNaS1zMZkP6nFRx9I2FjJXu6UZgeehZ915s56l/eTpAvDSbkT62T5qhB/rafRodm9ZSD9fBcc7SVvf9765nllg6Oz2/eJUtz3qyfbBgmZrroMDeWH6gb7boux2s3DCgT9CfrmMl7dAET7nFTKVFpKR/slD5k59/Dqw/giFy3O/9wSAyzkuiosqcIKroeP5JIwgco7ks3HPyF/QJf0F92yxWDb/RmloC2EIUfltg1I8fDHqD3mdBvUN9SZgo6Bc05WYKHtz0ekAtnvNCK2qtrWHXU0trjDzrWwigNLBruka4sZxAo4C1wTHG3wAm27d6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateZipped {
            get {
                return ResourceManager.GetString("CreateZipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAAC3u/e79LkH+AQrCzh6uvo4Knm4JrhGdwSLBCcVJKhoKzY7Czo4urNS8XdkXJiTk5SYnJ2QQVFpcmFScXZRaUZObnFRM2NqmMoJrUguRMwiaVFqcWIVQBAOPdp4/tAAAA.
        /// </summary>
        internal static string DropZipped {
            get {
                return ResourceManager.GetString("DropZipped", resourceCulture);
            }
        }
    }
}
