//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Persistence.Dapper.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PgSqlDatabaseRequests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PgSqlDatabaseRequests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Persistence.Dapper.Setup.PgSqlDatabaseRequests", typeof(PgSqlDatabaseRequests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAA/+1b3XKbSBa+tp6iy5UtS7salX/iOB7XXCDUspnIoAHkTPaGwoAsKhIo/DjjebW92EfaV9jTTYP4B0t4Jxfrqig2nD59+L6vu89pWv/5179/+gktFCwrSOHv8D3X42XMqZj9hYQpEiUV4d8FRVVQ6FuefxObqNx4hsssRuSz1+8h+LFNBN4FbkatxMVsNqTXiYmjbyxkrHRPNwLLQ8+692I7T/3L0wHipdmM9LF90gw90Nfu0+jYtJZ6uA6Oc562uu9/dz2zxNPZ6fnFq3x51pPtgwfL1FwHBfbG8gN9s0Xf7WDlhgG9gv50HStphyZ4yi1mKr1F7vRPFip/8vPPgfVHMESO+70/GETOeUlUVJkTRBUdzz9pBIFjNJeFe07+gj7hL6hvm0XT8Bu11BLAFqLw2wKjfnxh0Bv0PgvqHepLwkRBv6ApN1Pw4KbXA2rxnBdaUWttDbueWmox8qxvIYDSwK7pGuHGcgKNAtYGxxh/A5hs3+oV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateZipped {
            get {
                return ResourceManager.GetString("CreateZipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAAC3u/e79LkH+AQrCzh6uvo4Knm4JrhGdwSLBCcVJKhoKzY7Czo4urNS8XdkXJiTk5SYnJ2QQVFpcmFScXZRaUZObnFRM2NqmMoJrUguRMwiaVFqcWIVQBAOPdp4/tAAAA.
        /// </summary>
        public static string DropZipped {
            get {
                return ResourceManager.GetString("DropZipped", resourceCulture);
            }
        }
    }
}
