//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Persistence.Dapper.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PgSqlDatabaseRequests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PgSqlDatabaseRequests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Persistence.Dapper.Setup.PgSqlDatabaseRequests", typeof(PgSqlDatabaseRequests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAA/+1b3XKbSBa+tp6iy5UtS7salX/iOB7XXCDUspnI4AHkTOaGwoAsKhLI/DjjebW92EfaV9jTTYP4B0t4kotNVZQITp8+fN/X3ec0rf/++z8//YTmCpYVpPA3+Jbr8TLmVMy+IWGKRElF+HdBURUU+pbnX8UmKjee4TKLEfns9XsI/tgmAu8CN6NW4nw2G9LrxMTR1xYylrqnG4HloWfde7Gdx/758QDx0mxG+tg8aoYe6Cv3cXRoWgs9XAWHOU8b3fe/uZ5Z4unk+PTsVb4869H2wYNlaq6DAntt+YG+3qBvdrB0w4BeQX+5jpW0QxM85eYzld4id/pHc5U/+vnnwPozGCLH/dYfDCLnvCQqqswJoooO7z5pBIFDdCcLt5z8BX3CX1DfNoum4RO11BLA5qLw2xyjfnxh0Bv0PgvqDepLwkRBv6ApN1Pw4KrXA2rxHS+0otbaGHY9tdRi5FlPIYDSwK7pGuHacgKNAtYGxxh/A5hs3+oV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateZipped {
            get {
                return ResourceManager.GetString("CreateZipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAAC3u/e79LkH+AQrCzh6uvo4Knm4JrhGdwSLBCcVJKhoKzY7Czo4urNS8XdkXJiTk5SYnJ2QQVFpcmFScXZRaUZObnFRM2NqmMoJrUguRMwiaVFqcWIVQBAOPdp4/tAAAA.
        /// </summary>
        public static string DropZipped {
            get {
                return ResourceManager.GetString("DropZipped", resourceCulture);
            }
        }
    }
}
