//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTnT.Persistence.Dapper.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PgSqlDatabaseRequests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PgSqlDatabaseRequests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasTnT.Persistence.Dapper.Setup.PgSqlDatabaseRequests", typeof(PgSqlDatabaseRequests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAA/81b3XKbShK+tp5iyuUtS7s6Kv/EcXxc5wKhkc2JDD6A7JO9oTAgi4oECj/O8b7aXuwj7StszzAg/sES3iRVUSLo6en5vp6e7pnRf//9n19+QXMFywpS+Ft8x/V4GXMqZt+QMEWipCL8p6CoCgp9y/OvYxGVG89wmcSIfPb6PQR/bBOBdoGbUSlxPpsN6XMi4uhrCxlL3dONwPLQi+692s5z/+JkgHhpNiN9bJ41Qw/0lfs8OjSthR6ugsOcpo3u+99dzyzRdHpydv4mXZ71bPugwTI110GBvbb8QF9v0Hc7WLphQJ+gf7mOlbRDEzzl5jOVviJv+sdzlT/+9dfA+isYIsf93h8MIuW8JCqqzAmiig7vP2sEgUN0Lwt3nPwFfcZfUN82i6LhNyqpJYDNReGPOUb9+MGgN+g9Cuot6kvCREG/oSk3U/DgutcDavE9L7Si1toYdj21VGLkWd9CAKWBXdM1wrXlBBoFrA2OMf4GMNm+1RvQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateZipped {
            get {
                return ResourceManager.GetString("CreateZipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAAC3u/e79LkH+AQrCzh6uvo4Knm4JrhGdwSLBCcVJKhoKzY7Czo4urNS8XdkXJiTk5SYnJ2QQVFpcmFScXZRaUZObnFRM2NqmMoJrUguRMwiaVFqcWIVQBAOPdp4/tAAAA.
        /// </summary>
        public static string DropZipped {
            get {
                return ResourceManager.GetString("DropZipped", resourceCulture);
            }
        }
    }
}
