name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build -c Release

    - name: Prepare PostGreSQL test database
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: fastnt_test
        postgresql user: fastnt_user
        postgresql password: pwd
    - name: Setup Integration Tests connectionstring
      run: dotnet user-secrets set ConnectionStrings:FasTnT.Database "Server=localhost;Database=fastnt_test;Port=5432;User Id=fastnt_user;Password=pwd;" -p test/FasTnT.IntegrationTests/FasTnT.IntegrationTests.csproj
      
    - name: Run Unit Tests with Coverage
      run: dotnet test -c Debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
